# NumPy Pre-Class Exercises 

We've learned about NumPy and Numpy built-in methos. Let's test your knowledge. (Refer to the pre-class video for the answers)

Import Numpy

In [5]:
import numpy as np

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [6]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [7]:
np.array(my_list)

array([1, 2, 3, 4])

In [10]:
my_matrix = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [11]:
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,13,3)

array([ 0,  3,  6,  9, 12])

### zeros and ones

Generate arrays of zeros or ones

In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [22]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

## eye

Creates an identity matrix

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [24]:
np.random.rand(5)

array([0.74561087, 0.0323713 , 0.69479316, 0.99354096, 0.84461968])

In [25]:
np.random.rand(4,4)

array([[0.8764135 , 0.7417155 , 0.21756934, 0.01483133],
       [0.11709285, 0.89124608, 0.77829846, 0.0912042 ],
       [0.526833  , 0.58939324, 0.09728642, 0.20066964],
       [0.45396148, 0.3137575 , 0.21357478, 0.35579084]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [26]:
np.random.randn(3)

array([-0.11431666, -0.2108306 ,  0.21007157])

In [27]:
np.random.randn(4,4)

array([[-0.91916444,  1.14491492, -0.69840677,  0.1964954 ],
       [-0.1970932 ,  1.94645887,  0.01187273,  0.17417818],
       [-1.35245649, -0.32813166,  0.06435282, -0.38382386],
       [-0.03104711, -1.38359356,  0.16224952, -0.15984935]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [28]:
np.random.randint(1,100)

22

In [29]:
np.random.randint(1,100,10)

array([67, 99, 16, 17, 82, 95, 87, 10, 92, 78])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([49, 14,  6, 18, 46, 12,  9,  6, 29, 18])

## Reshape
Returns an array containing the same data with a new shape.

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
ranarr

array([49, 14,  6, 18, 46, 12,  9,  6, 29, 18])

In [41]:
ranarr.max()

49

In [42]:
ranarr.argmax()

0

In [43]:
ranarr.min()

6

In [44]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [45]:
arr.shape

(25,)

In [47]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(1,25).shape

(1, 25)

In [49]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [50]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [51]:
arr.dtype

dtype('int32')

# Great Job!